sevo_auth/urls.py
from django.urls import path

from .views import sign_up, index, sign_in, sign_out, change_user_data, change_password, set_new_password, forgot_password, delete

urlpatterns = [
    path("sign-up/", sign_up, name="sevo-auth-sign-up"),
    path("sign-in/", sign_in, name="sevo-auth-sign-in"),
    path("sign-out/", sign_out, name="sevo-auth-sign-out"),
    path("change-user-data/", change_user_data, name="sevo-auth-change-user-data"),
    path("change-password/", change_password, name="sevo-auth-change-password"),
    path("forgot-password/", forgot_password, name="sevo-auth-forgot-password"),
    path("set-new-password/<str:token>/", set_new_password, name="sevo-auth-set-new-password"),
    path("delete/", delete, name="sevo-auth-delete"),
    path("", index, name="sevo-auth-index")
]

sevo_cms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sevo_sites2 import views as site2_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path("", site2_views.homepage, name="index"),
    #path("auth/", include("sevo_auth.urls")),
    path("user/", include("sevo_user.urls")),
    path("pages/", include("sevo_sites2.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sevo_sites2/urls.py
from django.urls import path


from .views import index, detail



app_name = "sevo_sites2"
urlpatterns = [
    path("", index, name="index"),
    path("<slug:slug>/", detail, name="detail")
]

sevo_user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import DashboardView, SignInView, SignOutView, SignUpView, ChangePasswordView, ChangeUserData, DeleteUserView, ResetPasswordView

app_name = "sevo_user"
urlpatterns = [
    #path("", index, name="index"),
    path("dashboard/", DashboardView.as_view(), name="index"),

    path("sign-up/", SignUpView.as_view(), name="sign_up"),

    path("sign-in/", SignInView.as_view(), name="sign_in"), 

    path("sign-out/", SignOutView.as_view(), name="sign_out"),

    path("password-change", ChangePasswordView.as_view(), name="password_change"), 
    path("userdata-change/<int:pk>", ChangeUserData.as_view(), name="update"),
    path("user-delete/<int:pk>", DeleteUserView.as_view(), name="delete"),
    path("password-reset/", ResetPasswordView.as_view(), name="password_reset"),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name='sevo_user/password_reset_confirm.html', success_url=reverse_lazy("sevo_user:password_reset_complete")), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='sevo_user/password_reset_complete.html'), name='password_reset_complete'),

]

# https://dev.to/earthcomfy/django-reset-password-3k0l

templates/partials/_footer.html
<footer class="bg-black text-white py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-4 mb-2">
                <h4>Navigation</h4>
                <ul>
                    {% for pmenu in menu_main.get_published_pagemenus %}
                        <li>
                            <a href="{{ pmenu.get_page.get_absolute_url }}">{{ pmenu.get_page.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-4 mb-2">
                <h4>Meta</h4>
                <ul>
                    {% for pmenu in menu_meta.get_published_pagemenus %}
                        <li>
                            <a href="{{ pmenu.get_page.get_absolute_url }}">{{ pmenu.get_page.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-4 mb-2">
                <h4>Contact</h4>
            </div>
        </div>
    </div>
</footer>

templates/partials/_nav.html
{% load sevo_tags static i18n %}
<nav class="navbar bg-primary navbar-expand-lg shadow" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">SEVO CMS</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% for item in menu_primary.get_published_menu_sites %}
                {% if not item.has_subsites %}
                    <li class="nav-item"> 
                        <a class="nav-link {% is_active_site path=request.path site=item.site2 %}" href="{% if item.site2.available %}{{ item.site2.get_absolute_url }}{% endif %}">{{ item.site2.title }}</a>
                    </li>
                {% else %}
                    <li class="nav-item dropdown"> 
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ item.site2.title }}</a>
                        <ul class="dropdown-menu" data-bs-theme="light">
                            {% for subsite in item.get_published_subsites %}
                            <li>
                                <a class="dropdown-item {% is_active_site path=request.path site=subsite %}" href="{% if subsite.available %}{{ subsite.get_absolute_url }}{% endif %}">{{ subsite.title }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
            {% endfor %}
          {% comment %} <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li> {% endcomment %}

        </ul>
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <img class="opacity-75" src="{% static 'images/icons/user.svg' %}" alt="User">
              </a>
              <ul class="dropdown-menu dropdown-menu-end" data-bs-theme="light">
                {% if request.user.is_authenticated %}
                  <li>
                    <a class="dropdown-item" href="{% url 'sevo_user:index' %}">{% trans "Dashboard" %}</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'sevo_user:update' pk=request.user.id %}">{% trans "Change userdate" %}</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'sevo_user:password_change' %}">{% trans "Change password" %}</a>
                  </li>
                  <li>
                    <form method="post" action="{% url 'sevo_user:sign_out' %}">
                      {% csrf_token %}
                      <button class="btn btn-link dropdown-item">{% trans "Sign out" %}</button>
                  </form>
                  </li>
                {% else %}
                  <li>
                    <a class="dropdown-item" href="{% url 'sevo_user:sign_in' %}">{% trans "Sign in" %}</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'sevo_user:sign_up' %}">{% trans "Sign up" %}</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'sevo_user:password_reset' %}">{% trans "Forgot password" %}</a>
                  </li>
                {% endif %}
              </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/partials/_navbar.html
<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'homepage' %}">SEVO TEST</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% for pmenu in menu_main.get_published_pagemenus %}
                <li class="nav-item"> 
                    <a class="nav-link {% is_active_page path=request.path page=pmenu.get_page %}" href={{ pmenu.get_page.get_absolute_url }}>{{ pmenu.get_page.title }}</a>
                </li>
            {% endfor %}
          {% comment %} <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li> {% endcomment %}

        </ul>
      </div>
    </div>
  </nav>



  <h3>Primary</h3>
<ul>
    {% for item in menu_primary.get_published_menu_sites %}
        <li class="nav-item">
            
            <a class="nav-link {% is_active_site path=request.path site=item.site2 %}" href="{% url 'sevo_sites2:detail' item.site2.slug %}">{{ item.site2.title }}</a>
            {% if item.has_subsites %}
                <ul>
                    {% for subsite in item.get_published_subsites %}
                    <li>
                        <a href="{% url 'sevo_sites2:detail' subsite.slug %}">{{ subsite.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>

    {% endfor %}
</ul>