sevo_auth/urls.py
from django.urls import path

from .views import sign_up, index, sign_in, sign_out, change_user_data, change_password, set_new_password, forgot_password, delete

urlpatterns = [
    path("sign-up/", sign_up, name="sevo-auth-sign-up"),
    path("sign-in/", sign_in, name="sevo-auth-sign-in"),
    path("sign-out/", sign_out, name="sevo-auth-sign-out"),
    path("change-user-data/", change_user_data, name="sevo-auth-change-user-data"),
    path("change-password/", change_password, name="sevo-auth-change-password"),
    path("forgot-password/", forgot_password, name="sevo-auth-forgot-password"),
    path("set-new-password/<str:token>/", set_new_password, name="sevo-auth-set-new-password"),
    path("delete/", delete, name="sevo-auth-delete"),
    path("", index, name="sevo-auth-index")
]

sevo_cms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sevo_sites2 import views as site2_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path("", site2_views.homepage, name="index"),
    #path("auth/", include("sevo_auth.urls")),
    path("user/", include("sevo_user.urls")),
    path("pages/", include("sevo_sites2.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sevo_user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import DashboardView, SignInView, SignOutView, SignUpView, ChangePasswordView, ChangeUserData, DeleteUserView, ResetPasswordView

app_name = "sevo_user"
urlpatterns = [
    #path("", index, name="index"),
    path("dashboard/", DashboardView.as_view(), name="index"),

    path("sign-up/", SignUpView.as_view(), name="sign_up"),

    path("sign-in/", SignInView.as_view(), name="sign_in"), 

    path("sign-out/", SignOutView.as_view(), name="sign_out"),

    path("password-change", ChangePasswordView.as_view(), name="password_change"), 
    path("userdata-change/<int:pk>", ChangeUserData.as_view(), name="update"),
    path("user-delete/<int:pk>", DeleteUserView.as_view(), name="delete"),
    path("password-reset/", ResetPasswordView.as_view(), name="password_reset"),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name='sevo_user/password_reset_confirm.html', success_url=reverse_lazy("sevo_user:password_reset_complete")), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='sevo_user/password_reset_complete.html'), name='password_reset_complete'),

]

# https://dev.to/earthcomfy/django-reset-password-3k0l

sevo_user/models.py
from django.db import models

# Create your models here.

sevo_user/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class SignUpForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",

            "email",
            "password1",
            "password2"
        ]
        

class SignInForm(AuthenticationForm):
    pass

sevo_user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from django.views.generic import FormView

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm

from django.views.generic import UpdateView, DeleteView, TemplateView, View

from django.contrib.auth import get_user_model

from . import settings

User = get_user_model()



from .forms import SignUpForm, SignInForm

# Create your views here.





class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "sevo_user/dashboard.html"
    login_url = reverse_lazy("sevo_user:sign_in")


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "title": _("User dashboard")
        })
        return context



class SignUpView(FormView):
    template_name = "sevo_user/sign_up.html"
    form_class = SignUpForm
    success_url = reverse_lazy(settings.SEVO_USER_SIGN_UP_REDIRECT_URL)



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            "title": _("Sign up"),
            "submit": _("Submit")
        })
        return context

    def form_valid(self, form):
        user = form.save(commit=False)
        form.save()
        #login(request=self.request, user=user)
        messages.add_message(self.request, messages.SUCCESS, _("You are signed up and logged in!"))
        return super().form_valid(form)
    


class SignInView(SuccessMessageMixin, LoginView):
    template_name = "sevo_user/sign_in.html"
    next_page = reverse_lazy(settings.SEVO_USER_SIGN_IN_REDIRECT_URL)
    success_message = _("You are signed in!")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "title": _("Sign in"),
            "submit": _("Submit")
        })
        return context



# sign out
# @login_required(login_url="sevo_user:sign_in")
# def sign_out(request):
#     logout(request)
#     messages.add_message(request, messages.SUCCESS, _("You are signed out!"))
#     return redirect("sevo_user:index")



class SignOutView(LoginRequiredMixin, SuccessMessageMixin, LogoutView):
    next_page = reverse_lazy(settings.SEVO_USER_SIGN_OUT_REDIRECT_URL)
    success_message = _("You are signed out!")

    login_url = reverse_lazy("sevo_user:sign_in")




class ChangePasswordView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy(settings.SEVO_USER_PASSWORD_CHANGE_REDIRECT_URL)
    template_name = "sevo_user/password_change.html"
    title = _("Password change")
    success_message = _("Password changed")

    login_url = reverse_lazy("sevo_user:sign_in")



    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        #context["submit_label"] = _("Submit")
        context.update({
            "title": "Password change",
            "submit": _("Submit")
        })
        return context


class ChangeUserData(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = User
    fields = [
        "username",
        "first_name",
        "last_name"
    ]
    template_name = "sevo_user/update.html"
    success_message = _("Userdata changed!")
    success_url = reverse_lazy(settings.SEVO_USER_UPDATE_REDIRECT_URL)

    login_url = reverse_lazy("sevo_user:sign_in")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "title": "Userdata change",
            "submit": _("Submit")
        })
        return context
    

class DeleteUserView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = User
    template_name = "sevo_user/delete.html"
    success_message = _("User deleted!")
    success_url = reverse_lazy(settings.SEVO_USER_DELETE_REDIRECT_URL)

    login_url = reverse_lazy("sevo_user:sign_in")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "title": "Delete account",
            "submit": _("Delete")
        })
        return context
    



class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'sevo_user/password_reset.html'
    email_template_name = 'sevo_user/password_reset_email.html'
    subject_template_name = 'sevo_user/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy(settings.SEVO_USER_RESET_PASSWORD_REDIRECT_URL)

    

sevo_user/templates/sevo_user/dashboard.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="w-50 mx-auto">
        <h1 class="mb-3">Hello, {{ request.user.username }}!</h1>
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h3>{{ title }}</h3>
            </div>
            <div class="list-group list-group-flush">
                {% if user.is_authenticated == False %}
                    <a class="list-group-item list-group-item-action" href="{% url 'sevo_user:sign_up' %}">{% trans "Sign up" %}</a>
                    <a class="list-group-item list-group-item-action" href="{% url 'sevo_user:sign_in' %}">{% trans "Sign in" %}</a>
                {% else %}
                    <a class="list-group-item list-group-item-action" href="{% url 'sevo_user:password_change' %}">{% trans "Change password" %}</a>
                    <a class="list-group-item list-group-item-action" href="{% url 'sevo_user:update' request.user.id %}">{% trans "Change userdata" %}</a>
                    <form method="post" action="{% url 'sevo_user:sign_out' %}">
                        {% csrf_token %}
                        <button class="border-top-0 border-start-0 border-end-0 list-group-item list-group-item-action">{% trans "Sign out" %}</button>
                    </form>
                    <a class="list-group-item list-group-item-action text-danger" href="{% url 'sevo_user:delete' request.user.id %}">{% trans "Delete account" %}</a>

                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

sevo_user/templates/sevo_user/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<div  class="w-50 mx-auto">

    <form method="POST">
        {% csrf_token %}
        <div class="card shadow">
            <div class="card-header">
                <h3>{{ title }}</h3>
            </div>
            <div class="card-body">
                <p>{% trans "Do you really want to delete your account" %} <strong>{{ object.username|upper }}</strong>?</p>
            </div>
            <div class="card-footer">
                <button class="btn btn-danger">{{ submit }}</button>
            </div>
        </div>
    </form>
    <div class="mt-3 d-flex gap-2 flex-column">
        <a class="back-link" href="#">{% trans "Back" %}</a>
    </div>
</div>

{% endblock %}

sevo_user/templates/sevo_user/form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                {{ field.label_tag }}
                {{ field|cut:">"|add:" class='form-control'>" }}
            </div>
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endfor %}
        <button class="btn btn-primary">{{ submit_label }}</button>
    </form>
{% endblock %}

sevo_user/templates/sevo_user/password_change.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="w-25 mx-auto">
        <form method="POST">
            {% csrf_token %}
            {% include "./partials/_fields.html" %}
        </form>
        <div class="mt-3 d-flex gap-0 flex-column">
            <a class="back-link" href="#">{% trans "Back" %}</a>
        </div>
    </div>


{% endblock %}

sevo_user/templates/sevo_user/password_reset.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="w-50 mx-auto">
        <form method="POST">
            {% csrf_token %}
                {% include "./partials/_fields.html" with title="Password forgot" submit="Submit" %}
        </form>
        <div class="mt-3 d-flex gap-0 flex-column">
            <a class="back-link" href="#">{% trans "Back" %}</a>
        </div>
    </div>

{% endblock %}

sevo_user/templates/sevo_user/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <p>Your password has been set.</p>
    <a href="{% url 'sevo_user:sign_in' %}">{% trans "Sign in" %}</a>
{% endblock %}

sevo_user/templates/sevo_user/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="w-25 mx-auto">
        <form method="POST">
            {% csrf_token %}
            {% include "./partials/_fields.html" with title="Enter new password" submit="Submit" %}
        </form>
    </div>
{% endblock %}

sevo_user/templates/sevo_user/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'sevo_user:password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

sevo_user/templates/sevo_user/sign_in.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<div class="w-25 mx-auto">
    <form method="POST">
        {% csrf_token %}

        {% include "./partials/_fields.html" %}

    </form>

    <div class="mt-3 d-flex gap-0 flex-column">
        <a class="back-link" href="#">{% trans "Back" %}</a>
        <a  href="{% url 'sevo_user:sign_up' %}">{% trans "Sign up" %}</a>
        <a  href="{% url 'sevo_user:password_reset' %}">{% trans "Forgot password" %}</a>
    </div>
</div>
{% endblock %}

sevo_user/templates/sevo_user/sign_up.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="w-50 mx-auto">
        <form method="POST">
            {% csrf_token %}
            {% include "./partials/_fields.html" %}
        </form>
        <hr>
        <div class="mt-3 d-flex gap-0 flex-column">
            <a class="back-link" href="#">{% trans "Back" %}</a>
            <a  href="{% url 'sevo_user:sign_in' %}">{% trans "Sign in" %}</a>
        </div>
    </div>

{% endblock %}

sevo_user/templates/sevo_user/update.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<div class="w-50 mx-auto">
    <h1 class="mb-3">{% trans "Hello" %}, <strong>{{ object.username|upper }}</strong>!</h1>
    <form method="POST">
        {% csrf_token %}
        {% include "./partials/_fields.html" %}
    </form>
    <div class="mt-3 d-flex gap-0 flex-column">
        <a class="back-link" href="#">{% trans "Back" %}</a>
        <a href="{% url 'sevo_user:password_change' %}">{% trans "Change password" %}</a>
        <a class="link-danger" href="{% url 'sevo_user:delete' request.user.id %}">{% trans "Delete account" %}</a>
    </div>
</div>
{% endblock %}